source/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// The following use has been added by and for Eclipse
use Illuminate\Support\Facades\Route;

// ===============================================
// PUBLIC PAGES ==================================
// ===============================================

// show a static view for the home page (resources/views/home.blade.php)
Route::get('/', array('as' => 'home', function() {
    return View::make('home');
}));

Route::get('info/main', array('as' => 'info', function() {
    return view('info.main');
}));

Route::get('vip/main', array('as' => 'vip', function() {
    return view('vip.main');
}));

// about page (resources/views/about.blade.php)
Route::get('about', array('as' => 'about', function() {
    return View::make('about');
}));

Route::get('test-html', array('as' => 'test', function() {
    return view('test-html');
}));

// Get a suggestions
Route::get('suggestions', 'SuggestionController@suggest')->name('suggestions');

// Public restaurants pages
Route::get('restaurants', 'RestaurantTagController@restaurantsFilter')->name('restaurants.main');
Route::get('restaurants/results', 'RestaurantController@results')->name('restaurants.results');
Route::get('restaurants/details/{id}', 'RestaurantController@details')->name('restaurants.details');
Route::get('restaurant/details/{id}', 'RestaurantController@detailsSingle')->name('restaurants.details.single');
Route::get('tags/autocomplete', 'RestaurantTagController@autocomplete')->name('tags.autocomplete');

// Public stores pages
Route::get('stores', 'StoreTagController@viewAllTags')->name('stores.main');
Route::get('stores/results', 'StoreController@results')->name('stores.results');
Route::get('stores/details/{id}', 'StoreController@details')->name('stores.details');
Route::get('store/details/{id}', 'StoreController@detailsSingle')->name('stores.details.single');

// Public bars pages
Route::get('bars', 'BarTagController@viewAllTags')->name('bars.main');
Route::get('bars/results', 'BarController@results')->name('bars.results');
Route::get('bars/details/{id}', 'BarController@details')->name('bars.details');
Route::get('bar/details/{id}', 'BarController@detailsSingle')->name('bars.details.single');

// Public karaoke pages
Route::get('karaokes', 'KaraokeTagController@viewAllTags')->name('karaokes.main');
Route::get('karaokes/results', 'KaraokeController@results')->name('karaokes.results');
Route::get('karaokes/details/{id}', 'KaraokeController@details')->name('karaokes.details');
Route::get('karaoke/details/{id}', 'KaraokeController@detailsSingle')->name('karaokes.details.single');

// Public clubs pages
Route::get('clubs', 'ClubTagController@viewAllTags')->name('clubs.main');
Route::get('clubs/results', 'ClubController@results')->name('clubs.results');
Route::get('clubs/details/{id}', 'ClubController@details')->name('clubs.details');

// ===============================================
// ADMIN SECTION =================================
// ===============================================
Route::middleware(['auth'])->prefix('admin')->group(function()
{
    // main page for the admin section (resources/views/admin/dashboard.blade.php)
    Route::get('/', function() {
        return view('admin.dashboard');
    })->name('admin.dashboard');

    // To switch debug mode ON or OFF or possibly some other setups
    Route::post('debug', 'AdminPanelController@debugModeSwitch')->name('debug.switch');

    // Restaurants CRUD
    Route::resource('restaurants','RestaurantAdminController');

    // RestaurantType CRUD
    // tuto https://www.codexworld.com/laravel-tutorial-crud-add-edit-delete-operations/
    Route::get('restaurantType', 'RestaurantTypeController@index')->name('restaurantType.index');
    Route::get('restaurantType/details/{id}', 'RestaurantTypeController@show')->name('restaurantType.details');
    Route::get('restaurantType/add', 'RestaurantTypeController@create')->name('restaurantType.add');
    Route::post('restaurantType/insert', 'RestaurantTypeController@store')->name('restaurantType.insert');
    Route::get('restaurantType/edit/{id}', 'RestaurantTypeController@edit')->name('restaurantType.edit');
    Route::post('restaurantType/update/{id}', 'RestaurantTypeController@update')->name('restaurantType.update');
    Route::get('restaurantType/delete/{id}', 'RestaurantTypeController@destroy')->name('restaurantType.delete');

    // Restaurant Tags CRUD
    Route::resource('restaurantTag','RestaurantTagController');

    // Restaurants Import Export
    Route::get('restaurantsFiles', function() {
        return view('admin.restaurantsFiles');
    })->name('restaurants.imex');
    Route::get('restaurants/export/{type}', 'RestaurantAdminController@export')->name('restaurants.export');
    Route::post('restaurants/import', 'RestaurantAdminController@importAlt')->name('restaurants.import');

    // Laravel's welcome page
    Route::get('laravel', function () {
        return view('admin.laravel');
    })->name('laravel');
});

// ===============================================
// Authentication ================================
// ===============================================
Auth::routes();
// For admin auth see https://laracasts.com/discuss/channels/laravel/user-admin-authentication

source/app/Restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Restaurant extends Model
{
    // Uses a trait to get localisation related stuff
    use Traits\Location;

    // Accessible fields for mass update/create
    /* protected $fillable = [
        'name',
        'location',
        'lat',
        'lon',
        'type',
        'lunch_price',
        'points',
        'experience',
        'visited',
        'visit_date',
        'google_maps_link',
        'tabelog_link',
        'official_website',
        'score_lunch',
        'score_place',
        'score_food',
        'score_price',
        'score_date'
    ]; */

    /**
     * The tags that belong to the restaurant.
     * Read from the DB
     */
    public function tags()
    {
        return $this->belongsToMany(RestaurantTag::class);
    }

    /**
     * Returns the tags that belong to the restaurant.
     * Read from the cache
     * https://ctf0.wordpress.com/2017/08/19/how-to-cache-models-relationships-in-laravel/
     */
     public function tagsCached()
     {
         $cacheKey = strtolower(class_basename($this)).'-'.$this->id.'-tags';
         \Debugbar::debug('Cache key for those tags: '.$cacheKey);
         return \Cache::rememberForever($cacheKey, function () {
             \Debugbar::debug('Caching tags from DB: '.$this->tags);
             return  $this->tags;
         });
     }

    /**
     * Attach the given tags (that must already exist) to the restaurant
     */
    public function attachTags($labels)
    {
        if (!empty($labels))
        {
            // Get tags from the DB
            $query = (new RestaurantTag)->newQuery();
            foreach ($labels as $label)
            {
                $query->orWhere('label', '=', $label);
            }
            $tags = $query->get();
            // Attach them
            $this->tags()->attach($tags);
        }
        // Note:
        // attach just associate existing records: http://laraveldaily.com/pivot-tables-and-many-to-many-relationships/
        // otherwise use save or saveMany
        // awesome https://m.dotdev.co/writing-advanced-eloquent-search-query-filters-de8b6c2598db
    }

    /**
    * The users who have visited the restaurant
    */
    public function users()
    {
        //return $this->belongsToMany(User::class);
        //return $this->belongsToMany('App\User','user_restaurant')->withPivot('comment');
        return $this->belongsToMany(User::class)->withPivot('comment');
    }

}

source/app/RestaurantType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RestaurantType extends Model
{
    // tuto: https://www.codexworld.com/laravel-tutorial-crud-add-edit-delete-operations/
    protected $fillable = ['label'];
}

source/app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RestaurantController extends PlaceController
{
    /** Name of the model used for DB and views */
    const MODEL_NAME = 'Restaurant';

    public function getModelName()
    {
        return self::MODEL_NAME;
    }

    /**
     * Get the list to display.
     * TODO: implement "see more" button
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function results(Request $request)
    {
        // -----------------------------------
        // Reads request parameters

        // Operator for the Tags
        $op = request('op');

        // tags as a comma separated list
        $tags = request('tags');
        // makes tag into a traversable array
        $this->formatTags($tags);

        // Current position from client's GPS
        $position = request('position');

        // the sorting order for the result list
        $orderBy = request('orderBy');

        // -----------------------------------
        // Reads from cache or DB
        $places = $this->useCache($tags, $op, $orderBy);

        // -----------------------------------
        // Calculate distances from position, and sort them if required
        $places = $this->handleDistances($places, $position, $orderBy);

        // -----------------------------------
        // Shorten the points to display in list
        foreach ($places as $place) {
          $place->points = $this->ellipsis($place->points, 50);
        }

        // Keeps the input of the user interface
        // https://laravel.com/docs/5.5/requests#old-input
        // TODO: check if working or if useful?
        $request->flash();

        // Return the view with the resulted places
        return view($this->getModelResultsDataView(), compact('places'));
    }

    /**
     * Display the specified resource in one-apge view
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function details($id)
    {
        $class = $this->getModelClass();
        $place = $class::find($id);
        return view($this->getModelDetailsView(), compact('place'));
    }

    /**
     * Display the specified resource in independent page
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function detailsSingle($id)
    {
        $class = $this->getModelClass();
        $place = $class::find($id);
        return view($this->getModelDetailsView(true), compact('place'));
    }
}

source/resources/views/admin/restaurants/create.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Create')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New restaurant</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('restaurants.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) < 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::open(array('route' => 'restaurants.store','method'=>'POST')) !!}
         @include('admin.restaurants.form')
    {!! Form::close() !!}

@endsection

source/resources/views/admin/restaurants/edit.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Edit')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit restaurant</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('restaurants.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($restaurant, ['method' => 'PATCH','route' => ['restaurants.update', $restaurant->id]]) !!}
        @include('admin.restaurants.form')
    {!! Form::close() !!}

@endsection

source/resources/views/admin/restaurants/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null,
                      array('placeholder' => 'Name',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Location:</strong>
            {!! Form::text('location', null,
                      array('placeholder' => 'Location',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Coordinates:</strong>
            {!! Form::text('coord', null,
                      array('placeholder' => 'Coordinates',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Type:</strong>
            {!! Form::text('type', null,
                      array('placeholder' => 'Type',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Typical lunch price:</strong>
            {!! Form::number('lunch_price', null,
                      array('placeholder' => 'Typical lunch price',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Points:</strong>
            {!! Form::textarea('points', null,
                      array('placeholder' => 'Points',
                            'class' => 'form-control',
                            'style'=>'height:100px')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Personal experience:</strong>
            {!! Form::textarea('experience', null,
                      array('placeholder' => 'Personal experience',
                            'class' => 'form-control',
                            'style'=>'height:150px')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Visited:</strong>
           {!! Form::radio('visited', true, true,
              array(
                'placeholder' => 'yes',
                'class' => 'form-control')) !!}
           {!! Form::radio('visited', false, false,
              array(
                'placeholder' => 'no',
                'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Visit date:</strong>
            {!! Form::date('visit_date', null,
                      array('placeholder' => 'Visit date',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Google Maps Link:</strong>
            {!! Form::url('google_maps_link', null,
                      array('placeholder' => 'Google Maps Link',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Tabelog Link:</strong>
            {!! Form::url('tabelog_link', null,
                      array('placeholder' => 'Tabelog Link',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Official Website:</strong>
            {!! Form::url('official_website', null,
                      array('placeholder' => 'Official Website',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Score Global:</strong>
            {!! Form::number('score_lunch', null,
                      array('placeholder' => 'Score Lunch',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Score Place:</strong>
            {!! Form::number('score_place', null,
                      array('placeholder' => 'Score Place',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Score Food:</strong>
            {!! Form::number('score_food', null,
                      array('placeholder' => 'Score Food',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Score Price:</strong>
            {!! Form::number('score_price', null,
                      array('placeholder' => 'Score Price',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Score Date:</strong>
            {!! Form::number('score_date', null,
                      array('placeholder' => 'Score Date',
                            'class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

source/resources/views/admin/restaurants/index.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Index')

@section('content')
<div id="content">

    <h2>Restaurants CRUDIX [ currently displaying {{ $restaurants->count() }} ]</h2>

    <div>
        <a href="{{ route('restaurants.create') }}"> Create New restaurant</a>
        <a href="{{ route('restaurants.imex') }}"> ImEx restaurant</a>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table>
      <tr>
          <th>No</th>
          <th>Name</th>
          <th>Type</th>
          <th>Tags</th>
          <th>lunch</th>
          <th>food</th>
          <th>place</th>
          <th>price</th>
          <th>date</th>
          <th>lat</th>
          <th>lon</th>
          <th>map</th>
          <th>tabelog</th>
          <th>official</th>
          <th>Action</th>
      </tr>
    @foreach ($restaurants as $restaurant)
      <tr>
          <td>{{ $restaurant->id }}</td>
          <td>{{ $restaurant->name }}</td>
          <td>{{ $restaurant->type }}</td>
          <td>
            @foreach ($restaurant->tags as $tag)
              {{ $tag->label }} |
            @endforeach
          </td>
          <td>{{ $restaurant->score_lunch }}</td>
          <td>{{ $restaurant->score_food }}</td>
          <td>{{ $restaurant->score_place }}</td>
          <td>{{ $restaurant->score_price }}</td>
          <td>{{ $restaurant->score_date }}</td>
          <td>{{ number_format($restaurant->lat, 4, '.', ',') }}</td>
          <td>{{ number_format($restaurant->lon, 4, '.', ',') }}</td>
          <td class="center">
            <a target="_blank"
              href="{{ $restaurant->google_maps_link }}">
              map</a>
          </td>
          <td class="center">
            <a target="_blank"
              href="{{ $restaurant->tabelog_link }}">
              link</a>
          </td>
          <td class="center">
            <a target="_blank"
              href="{{ $restaurant->official_website }}">
              site</a>
          </td>
          <td>
              <a href="{{ route('restaurants.show', $restaurant->id) }}">Show</a>
              <a href="{{ route('restaurants.edit', $restaurant->id) }}">Edit</a>
              {!! Form::open(['method' => 'DELETE','route' => ['restaurants.destroy', $restaurant->id],'style'=>'display:inline']) !!}
              {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
              {!! Form::close() !!}
          </td>
      </tr>
    @endforeach
    </table>

</div>
@endsection

source/resources/views/admin/restaurants/show.blade.php
@extends('layouts.app')

@section('title', 'Restaurant Show')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show restaurant</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('restaurants.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $restaurant->name}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Location:</strong>
                {{ $restaurant->location}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Coordinates:</strong>
                {{ $restaurant->coord}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Type:</strong>
                {{ $restaurant->type}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Lunch price:</strong>
                {{ $restaurant->lunch_price}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Points:</strong>
                {{ $restaurant->points}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Personal experience:</strong>
                {{ $restaurant->experience}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Visited:</strong>
                {{ $restaurant->visited}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Visit date:</strong>
                {{ $restaurant->visit_date}}
            </div>
        </div>
    </div>
@endsection